source 'https://rubygems.org'
ruby '2.5.1'
gem 'pry'
gem 'rspec'
gem 'rubocop', '~> 0.57.2'
gem 'dotenv'
gem 'nokogiri'
gem 'xpath'
gem 'json'
gem 'google_drive'
gem 'colorize'
gem 'google-api-client', '~> 0.8'
gem 'googleauth'
gem 'fileutils'
gem 'mime'
gem 'csv'
